### PR TITLE
Flippers change

### PR DESCRIPTION
**Pull request by artisticLogicMK**
Implemented changes pertaining to the issue i submitted; https://github.com/animate-css/animate.css/issues/1572

### CODE REVIEW

**Comment by warengonzaga** [comment]
do you have a codepen for a preview of your changes? Also how it is also different from my recent PR? #1580

**Comment by artisticLogicMK** [comment]
> do you have a codepen for a preview of your changes? Also how it is also different from my recent PR? #1580
Yours is okay. It fixes the problem fine. 🖤

**Comment by artisticLogicMK** [comment]
> do you have a codepen for a preview of your changes? Also how it is also different from my recent PR? #1580

Yours is okay. It fixes the problem fine. 🖤

**Comment by warengonzaga** [comment]
> > do you have a codepen for a preview of your changes? Also how it is also different from my recent PR? #1580
> 
> Yours is okay. It fixes the problem fine. 🖤

yeah forgot the file name from the previous PR.

**Comment by warengonzaga** [comment]
feel free to close this @eltonmesquita

**Pull request closed without merging**
