### PR TITLE
Add "return" operator to Promise in animateCSS

### PR DESCRIPTION
**Pull request by edbond88**
Fixed example in documentation

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
Thanks for the PR @edbond88.

Hi @eltonmesquita kindly review this...

**Review by WarenGonzaga — APPROVED** [review]
Looks good to me...

**Comment by eltonmesquita** [comment]
Thanks for the PR @edbond88. Could you please clone the project, install de dependencies and run `npm run docs` so it will be published on our website?

**Comment by edbond88** [comment]
@eltonmesquita I have generated documentation. During the generation, I noticed that the tag "a" in footer is not closed so I closed it.

**Review by eltonmesquita — APPROVED** [review]

**Comment by eltonmesquita** [comment]
Nice catch! Thanks for the PR.

**Pull request merged**
