### PR TITLE
📝 Fixed typo

### PR DESCRIPTION
**Pull request by umutambyi-gad**
just fixed simple typo in docs (01-usage.md)

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
Good catch! @umutambyi-gad Please check @eltonmesquita

**Review by WarenGonzaga — APPROVED** [review]

**Comment by eltonmesquita** [comment]
Thanks for the PR @umutambyi-gad ! Can you please run `npm run docs` locally and update the commit so it will get reflected on the live website?

**Review by eltonmesquita — CHANGES_REQUESTED** [review]
Please run `npm run docs` so the website can be rebuilt and published. You just need to:
```
gh repo clone animate-css/animate.css
cd animate.css
npm install
npm run docs
git add .
git commit --amend
git push --force-with-lease

**Comment by WarenGonzaga** [comment]
Hi @umutambyi-gad update on this? Can you please fix the issue?

**Review by eltonmesquita — APPROVED** [review]

**Pull request merged**
