### PR TITLE
Adds iOS shake animation

### PR DESCRIPTION
**Pull request by anthony0030**
Signed-off-by: Anthony Veaudry <anthony@veaudry.pro>

### CODE REVIEW

**Comment by eltonmesquita** [comment]
Thanks for the PR @anthony0030. Please read our [contributing section](https://github.com/animate-css/animate.css#contributing):

> Pull requests are the way to go here. We only have two rules for submitting a pull request: match the naming convention (camelCase, categorised [fades, bounces, etc]) and let us see a demo of submitted animations in a pen.

**Comment by anthony0030** [comment]
Thanks @eltonmesquita ,

It would be great to add that a pen is required in the CONTRIBUTING.md.

Here is the pen: https://codepen.io/anthony0030/pen/ExPBexv

Thanks again for your time :)

**Comment by eltonmesquita** [comment]
Thanks for the pen! I appreciate the hard work. 😃 

Honestly, I think this looks way too much with our current `tada` animation. At the moment I don't see why to merge it. About the contribution guide, you're right, it's missing in the guide. You'd like to send a PR fixing that?

**Comment by anthony0030** [comment]
I can agree it is similar but more subtle, it is an animation I use in conjunction with animate.css on some of my projects.
What I do is if I have a useful code addition I make a pull request to the repo that the code is for. That way others can use the same code, I can just install the npm package without copying the code to every new repo I need to use it in and the best scenario is someone improves my code. Here is the pull request for the documentation you asked me for https://github.com/animate-css/animate.css/pull/1089

**Comment by daneden** [comment]
Hey @anthony0030! I think I have to side with @eltonmesquita here; this animation seems too similar to current ones in Animate.css, including `tada` and `shakeX`. I’m going to close this PR. I appreciate the submission, but thanks for also updating the contributor guidelines in #1089!

**Pull request closed without merging**
