### PR TITLE
Fix for 'Edit this on Github' links

### PR DESCRIPTION
**Pull request by jadlimcaco**
Noticed the edit links didn't work because the path was wrong so this fixes them.
Also fixed a small typo.

### CODE REVIEW

**Comment by jadlimcaco** [comment]
Noticed that I edited the static files instead of the actual source. Fixing that first.

**Comment by WarenGonzaga** [comment]
@eltonmesquita kindly check this...

**Comment by jadlimcaco** [comment]
@WarenGonzaga Okay, this is the correct fix so that the links for the markdown files are generated correctly by compileMD.js.

**Comment by WarenGonzaga** [comment]
@jadlimcaco did you properly compile this?

**Comment by jadlimcaco** [comment]
`npm run docs` right?

**Comment by eltonmesquita** [comment]
Thanks for that! I couldn't test it before releasing.

**Pull request merged**
