### PR TITLE
👌 IMPROVE: update CSSNano, add Security Policy

### PR DESCRIPTION
**Pull request by WarenGonzaga**
Update the CSSNano dev-Dependency. 😎

### CODE REVIEW

**Review by eltonmesquita — APPROVED** [review]
Just fix the conflict and we're good 😎

**Comment by WarenGonzaga** [comment]
Got it @eltonmesquita

**Comment by WarenGonzaga** [comment]
The security policy is also included here.

**Review by eltonmesquita — APPROVED** [review]
LGTM

**Pull request merged**
