### PR TITLE
docs: Fix simple typo, globaly -> globally

### PR DESCRIPTION
**Pull request by timgates42**
There is a small typo in docsSource/sections/01-usage.md, docsSource/sections/02-utilities.md.

Should read `globally` rather than `globaly`.

### CODE REVIEW

**Comment by eltonmesquita** [comment]
Nice catch! Thanks for that.

**Review by eltonmesquita — CHANGES_REQUESTED** [review]
Could you please run `npm run docs` in the repo?

**Comment by timgates42** [comment]
Thanks have pushed up the changes to the docs.

**Review by eltonmesquita — APPROVED** [review]

**Comment by eltonmesquita** [comment]
Thanks for that!

**Pull request merged**
