### PR TITLE
Add Security Policy

### PR DESCRIPTION
**Pull request by WarenGonzaga**
I just add a file for security policy. What do you think @eltonmesquita? Let me know!

### CODE REVIEW

**Review by eltonmesquita — APPROVED** [review]
LGTM

**Comment by eltonmesquita** [comment]
@WarenGonzaga just rebase/fix the conflict and we should be good to go 💯

**Comment by WarenGonzaga** [comment]
All good @eltonmesquita

**Comment by WarenGonzaga** [comment]
Closing this I add it on my main branch merge.

**Pull request closed without merging**
