### PR TITLE
Update animate.css

### PR DESCRIPTION
**Pull request by nithin2169**

### CODE REVIEW

**Comment by nithin2169** [comment]
.animate slide-repeat{
  animation-duration: 3s;
  animation-name: slidein;
  animation-iteration-count: infinite;
}


@keyframes slidein {
  from {
    margin-left: 100%;
    width: 300%;
  }

  to {
    margin-left: 0%;
    width: 100%;
  }
}

.animate sliderepeat-infinite {
  animation-duration: 3s;
  animation-name: slidein;
  animation-iteration-count: infinite;
  animation-direction: alternate;
}


@keyframes slidein {
  from {
    margin-left: 100%;
    width: 300%;
  }

  to {
    margin-left: 0%;
    width: 100%;
  }
}

**Review by nithin2169 — COMMENTED** [review]
this is the text effects which is add which is not available can you please see that

**Comment by eltonmesquita** [comment]
Sorry, but I don't understand what you're proposing in this PR. Care to add a few details in the description and if it's some sort of adjustment to any animation, please add a codepen's pen to the description too.

**Comment by eltonmesquita** [comment]
I'm closing this as there was no response.

**Pull request closed without merging**
