### PR TITLE
add gradient text anim

### PR DESCRIPTION
**Pull request by Masterbordbar**

### CODE REVIEW

**Comment by eltonmesquita** [comment]
Heya @Masterbordbar, thanks for the PR. Could you please follow the [contributing guide](https://github.com/animate-css/animate.css/blob/main/CONTRIBUTING.md#how-to-contribute) so we can effectively review it?

**Comment by Masterbordbar** [comment]
Did you like this animation?

**Comment by eltonmesquita** [comment]
I couldn't as you need to
> 4. Create a [pen](https://codepen.io/) demonstrating what your change will do.
Can you please do it?

**Comment by Masterbordbar** [comment]
@eltonmesquita  :)
https://codepen.io/masterbordbar/pen/YzeYYQq?editors=1100

**Comment by Masterbordbar** [comment]
**Photos** can also be used instead of gradients

**Comment by warengonzaga** [comment]
Good addition @Masterbordbar! 🔥 Looks good to me and I think it is useful for animating gradient text.
My only concern on this, this will have complex settings as we add customization to it. Not sure with @eltonmesquita decision on this.

**Comment by Masterbordbar** [comment]
@warengonzaga I am very happy and I will help as much as I can :)

**Comment by Masterbordbar** [comment]
Photo instead of gradient https://codepen.io/masterbordbar/pen/JjpMeqx !

**Pull request closed without merging**
