### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by daneden**
It was recently brought to my attention that Animate.css was used on a website soliciting tips for abortion bounties in Texas, where recent legislation outlawed safe access to abortion.

Abortion is a form of healthcare, and as such is a fundamental human right. By introducing this legislation, lawmakers in Texas are removing the bodily autonomy of women and endangering their well-being by forcing them to seek potentially unsafe alternatives.

Amnesty International [states](https://www.amnesty.org/en/what-we-do/sexual-and-reproductive-rights/abortion-facts/):
> Access to safe abortion services is a human right. Under international human rights law, everyone has a right to life, a right to health, and a right to be free from violence, discrimination, and torture or cruel, inhuman and degrading treatment.

Removal of access to abortion is one thing, but rewarding bounties for disclosure of information about women seeking abortions puts them in immense physical danger and is itself a violation of their human rights.

Not only this, but these legal changes are unconstitutional and the changes themselves violate international UN Human Rights laws. 

The [Universal Declaration of Human Rights (UDHR)](https://www.un.org/sites/un2.un.org/files/udhr.pdf) Article 21, Section 3 states:
> The will of the people shall be the basis of the authority of government

More than 60% of Americans believe people should be able to obtain abortions in the first trimester of pregnancy ([source](https://www.forbes.com/sites/alisondurkee/2021/06/25/majority-of-americans-support-abortion-poll-finds---but-not-later-in-the-pregnancy/?sh=d0d775250744)), and the current presidential administration have [themselves stated](https://www.theguardian.com/us-news/2021/sep/09/biden-administration-sue-texas-abortion-law) that abortion rights are “non-negotiable”.

I want to make it clear to the Animate.css community and the people who use Animate.css for their work and projects that we take a firm stance in support of women’s bodily autonomy and other forms of human rights, and do not permit the use of Animate.css on any project that impedes on these rights. To this end, I plan to update Animate.css’s license to the [Hippocratic License](https://firstdonoharm.dev), a variation of the currently-used MIT licence which also bans the use of licensed software in projects that violate human rights.

### CODE REVIEW

**Comment by tpritc** [comment]
This is a great change, and I'm all in-favor. Just as a note, if we're updating the license, we should also update [the license part of the README](https://github.com/animate-css/animate.css/blob/license-update/README.md#license) to reflect the change.

**Review by eltonmesquita — APPROVED** [review]
Thank you very much for this! 👏 👏 👏

**Comment by WarenGonzaga** [comment]
Updating the builds now...

**Comment by Aspie96** [comment]
Note: you should preserve the previous license text in the project, if you have had contributors prior to this.

See: https://github.com/vcr/vcr/issues/804
Also: https://ethicalsource.dev/blog/adopting-an-ethical-license/ (this one got writed as a consequence of the above).

**Pull request merged**
