### PR TITLE
Latest Updates for Animate.css v4

### PR DESCRIPTION
**Pull request by WarenGonzaga**
Hi @eltonmesquita I'm referencing #1066 this task... done with it.
Also for the issue #1102 is now fixed.

Kindly review this PR... thank you! Let me know if there is any changes...

### CODE REVIEW

**Review by eltonmesquita — APPROVED** [review]
Nice, thanks for that!

**Comment by eltonmesquita** [comment]
Tomorrow I'll merge this and release the new version.

**Comment by WarenGonzaga** [comment]
Awesome! Thanks @eltonmesquita ...

**Comment by eltonmesquita** [comment]
Hey @WarenGonzaga, I just noticed that you PR'ed to the `master` branch which is dead by now. Can you PR this to **`main`** instead?
BTW, @daneden I think we're good to delete the `master`. What do you think?

**Comment by WarenGonzaga** [comment]
Hi @eltonmesquita done.. I just change the base branch to main...

**Comment by daneden** [comment]
@eltonmesquita done!

**Review by eltonmesquita — APPROVED** [review]

**Pull request merged**
