### PR TITLE
Updated CDN URL

### PR DESCRIPTION
**Pull request by juansalcedo**

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
@juansalcedo thanks for the update! @eltonmesquita will check this update.

**Comment by JosephDunivan** [comment]
Hello, next time you make breaking changes, such as the class syntax, can you please give a 1 week update window. I spent 4 hours today trying to figure out what was wrong with my code. Before the documentation site was updated with the new syntax.

**Comment by WarenGonzaga** [comment]
Hi @JosephDunivan sorry for that... @daneden and @eltonmesquita I guess we need an official medium of communication to our users? Can I suggest? How about a discord server? I can manage the community if you allow me. I just created an official one here: [discord.gg/c4fjVk](https://discord.gg/c4fjVk)

**Comment by JosephDunivan** [comment]
You could also perhaps use push notifications with a service worker on the new website: https://animate.style
That way people that stumble upon it will receive those notifications if they subscribe. It won't catch everyone though. Maybe I'll do some investigating, there may be an rpm tool or npm related website that does this already.

**Comment by WarenGonzaga** [comment]
> You could also perhaps use push notifications with a service worker on the new website: https://animate.style
> That way people that stumble upon it will receive those notifications if they subscribe. It won't catch everyone though. Maybe I'll do some investigating, there may be an npm tool or npm related website that does this already.

Agree, thanks for your suggest but overall decision comes from @daneden anyway I will create a pull request for the community discord server.

**Comment by eltonmesquita** [comment]
I understand that this is frustrating but we follow the semantic versioning to avoid this kind of situation.

Note that when there's a major version release, you should never update right away as there are **breaking changes**. This applies to any library that follow semversion, which is the majority of the open-source software these days.

Besides, we made sure that the breaking changes were well documented and visible in our docs and that there was enough support for migrating. It's important to read the docs when updating a library so you won't go through this again.

There's no need for notifications about new versions or more channels for communication. The best thing is to get used to [semversion](https://semver.org/). It'll save you much time when using open source libraries.

**Comment by JosephDunivan** [comment]
This was unique in that I installed the plugin using the “animated” syntax from the previous version just as you were updating to the new website an syntax. Healthy habit to use version control in my node modules though yes. I think the issue is it just changed and the old website just said 404 and then was later updated on the GitHub readme. Perhaps it would still be ideal to release a message on animate.styles website in the future about breaking changes

**Comment by eltonmesquita** [comment]
I've compiled and merged it myself, as this is simple but quite important.

@JosephDunivan if you have any suggestion please feel free to open an issue. We've made our best to make a smooth transition but we're all working on our free time and the last release required a major effort from our part, so there was still some minor hiccups in the process of publishing the website.

Again, feel free to open an issue if you have any suggestion. Any new comment here will be ignored.

Cheers

**Pull request merged**
